<a href="https://colab.research.google.com/github/ssvas1997/TensorFlow-2.0-Examples/blob/master/Customer_churn_for_bank_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip uninstall tensorflow

Uninstalling tensorflow-1.15.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/freeze_graph
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-1.15.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-1.15.0


In [2]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 44kB/s 
     |████████████████████████████████| 3.0MB 35.4MB/s 
     |████████████████████████████████| 419kB 49.7MB/s 


In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [56]:
print(tf.__version__)

2.0.0-alpha0


In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
dataset = pd.read_csv("Customer_Churn_Modelling.csv")

In [59]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

Check Last Column - **Exited**
- 1 means customer is going to leave the bank
- 0 means customer is going to stay 

In [0]:
X= dataset.drop(labels=['RowNumber','CustomerId','Surname','Exited'],axis=1) 
# axis = 1 refers to the columns
#remove label from dataset and store it in different vector

In [0]:
y= dataset['Exited']
#y contains label 0 or 1

In [62]:
X.head(10)

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10
5          645     Spain    Male  ...          1               0        149756.71
6          822    France    Male  ...          1               1         10062.80
7          376   Germany  Female  ...          1               0        119346.88
8          501    France    Male  ...          0               1         74940.50
9          684    France    Male  ...          1               1         71725.73

[10 rows x 10 columns]

In [63]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

ANN doesn't understand Text. So we need to convert Text values into numerical values

In [0]:
from sklearn.preprocessing import LabelEncoder #Encode- Text to Numerical

In [0]:
label1 = LabelEncoder()
X["Geography"] = label1.fit_transform(X["Geography"]) #Convert geography names to numbers

In [66]:
X.head(10)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10
5          645          2    Male  ...          1               0        149756.71
6          822          0    Male  ...          1               1         10062.80
7          376          1  Female  ...          1               0        119346.88
8          501          0    Male  ...          0               1         74940.50
9          684          0    Male  ...          1               1         71725.73

[10 rows x 10 columns]

In Geography
- 0 refers to France
- 1 refers to Germany
- 2 refers to Spain

In [0]:
label2 = LabelEncoder()
X["Gender"] = label2.fit_transform(X["Gender"])

In [68]:
X.head(10)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10
5          645          2       1  ...          1               0        149756.71
6          822          0       1  ...          1               1         10062.80
7          376          1       0  ...          1               0        119346.88
8          501          0       1  ...          0               1         74940.50
9          684          0       1  ...          1               1         71725.73

[10 rows x 10 columns]

In Gender
- 0 refers to Female
- 1 refers to Male

We need to consider Geographical & Gender values as a categorical value and not as a number so we use One Hot Encoding

In [0]:
X = pd.get_dummies(X,drop_first=True,columns=['Geography'])

Geography has 3 values - 0, 1, 2

It would be divided into 2 columns 
- Geography_1
- Geography_2

For spain Geography_2 will have value 1

For Germany Geography_1 will have value 1

In [70]:
X.head(10)

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1
5          645       1   44  ...        149756.71            0            1
6          822       1   50  ...         10062.80            0            0
7          376       0   29  ...        119346.88            1            0
8          501       1   44  ...         74940.50            0            0
9          684       1   27  ...         71725.73            0            0

[10 rows x 11 columns]

We didn't do OHE for Gender column as it has only 2 values 0 and 1 which can be represented in 1 column

### Feature Standardization

As the data value varies from column to column we need to do standardization

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0,stratify=y)

stratify=y is used to divide the y data symmetrically

This stratify parameter makes a split so that the proportion of values in the sample produced will be the same as the proportion of values provided to parameter stratify.

For example, if variable y is a binary categorical variable with values 0 and 1 and there are 25% of zeros and 75% of ones, stratify=y will make sure that your random split has 25% of 0's and 75% of 1's.

In [0]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [74]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

Now all the column data values have come down to -3 to +3 i.e in the same scale

### Build ANN

In [92]:
X.shape #11 columns

(10000, 11)

In [0]:
model=Sequential()
#In the first layer you need to specify input_dim OR input_shape (For an image)
model.add(Dense(X.shape[1],activation='relu', input_dim= X.shape[1])) #Input Layer
model.add(Dense(128, activation='relu')) #Hidden layer
model.add(Dense(1, activation='sigmoid')) #Ouput layer 1 neuron which would say (0-Stay or 1-Exit)

In [0]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#adam uses stocasthic gradient descent
#binary_crossentropy because output will be 0 or 1 

In [108]:
#Since y_train was a panda object we need to convert into numpy array
#batch_size is used to calculate weights in stocasthic gradient descent based on the data points
#If batch_size = 1 then for every input it will update weights and takes more training time
#Here in this case for every 10 inputs update the weights
#verbose shows progress bar of the training
model.fit(X_train,y_train.to_numpy(),batch_size=10, epochs=7, verbose=1)

Epoch 1/7
8000/8000 [==============================] - 1s 145us/sample - loss: 0.4521 - accuracy: 0.8041
Epoch 2/7
8000/8000 [==============================] - 1s 132us/sample - loss: 0.3798 - accuracy: 0.8382
Epoch 3/7
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3573 - accuracy: 0.8515
Epoch 4/7
8000/8000 [==============================] - 1s 131us/sample - loss: 0.3496 - accuracy: 0.8562
Epoch 5/7
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3437 - accuracy: 0.8586
Epoch 6/7
8000/8000 [==============================] - 1s 132us/sample - loss: 0.3389 - accuracy: 0.8619
Epoch 7/7
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3377 - accuracy: 0.8610


In [0]:
y_pred= model.predict_classes(X_test)

In [110]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [111]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

y_pred element 0 is not correct as it is not same as y_test element 0

check the other values at the end 

In [118]:
#Calculate Accuracy
test_loss,test_acc=model.evaluate(X_test,y_test)

2000/2000 [==============================] - 0s 25us/sample - loss: 0.3480 - accuracy: 0.8575


In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [120]:
confusion_matrix(y_test,y_pred)

array([[1533,   60],
       [ 225,  182]])

In [121]:
accuracy_score(y_test,y_pred)

0.8575